### ISSUE TITLE
Failed to parse debug task using shell output

### ISSUE THREAD

**Issue by lmello** [RockProfile/Ansible-Output-Parser#23]
I have a shell task that register to a variable 
Then a debug task that receives this variable.

this is failing to parse.

do you mind if I improve the report and provide a pr with a fix ?

**Comment by petermcd** [comment]
Hi

By all means very happy to accept any pr’s. If you need any help just ask. 

Adding a test covering the output would be much appreciated as well if possible.

**Comment by petermcd** [comment]
Hi @lmello I am going to close this ticket for the momentr but feel free to post a new issue with some examples that fail to parse if you are unable to provide a pull request.

**Comment by vvzvlad** [comment]
[allora-134sxwwqce4_20240827_041834.log](https://github.com/user-attachments/files/16806077/allora-134sxwwqce4_20240827_041834.log)
I have encountered that I can't parse this file written from the console


```
with open(log_output_filename, 'w', encoding='utf-8') as deploy_log:
        process = subprocess.Popen( ['ansible-playbook', '-i', inventory_filename, playbook_file, '-v'],
                                    stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1 )
        
        for line in iter(process.stdout.readline, ''):
             deploy_log.write(line)
        process.stdout.close()
        return_code = process.wait()
        deploy_log.flush()    
        
```
