### ISSUE TITLE
Warnings by parse play

### ISSUE THREAD

**Issue by vvzvlad** [RockProfile/Ansible-Output-Parser#31]
```
WARNING: Failed parsing line 'ASYNC OK on allora-134sxwwqce4: jid=709958327516.840'
WARNING: Failed parsing line 'ASYNC OK on allora-134sxwwqce4: jid=489004506289.1323'
WARNING: Failed parsing line 'ASYNC POLL on allora-134sxwwqce4: jid=687805291581.1868 started=1 finished=0'
WARNING: Failed parsing line 'ASYNC POLL on allora-134sxwwqce4: jid=687805291581.1868 started=1 finished=0'
WARNING: Failed parsing line 'ASYNC OK on allora-134sxwwqce4: jid=687805291581.1868'
WARNING: Failed parsing line 'ASYNC OK on allora-134sxwwqce4: jid=516878415303.3522'
```
[allora-134sxwwqce4_20240827_041834.log](https://github.com/user-attachments/files/16806194/allora-134sxwwqce4_20240827_041834.log)

**Comment by petermcd** [comment]
Hi @vvzvlad  thanks for the report and example log. I will hopefully have a chance to look at this over the weekend.

**Comment by petermcd** [comment]
Apologies for the delay and thank you for highlighting. I have resolved this in a recent merge. If using this package from git simply update.

I will update pypi in a while, I wish to add some further testing prior to doing this.
